version: "3.8"
services:
  nginx:
    container_name: nginx_server
    image: nginx
    command: nginx -g "daemon off;"
    ports:
      - "88:80"
    volumes:
      - ./dist:/usr/share/nginx/html/
    restart: always
